#!/usr/bin/python2
from ase.io.vasp import read_vasp,write_vasp
from ase.visualize import view
from sys import argv,stdout
if (len(argv)!=2):
	stdout.write("Usage: ase_wrap struct \n");
else:
	filename=argv[1]
	struct=read_vasp(filename);

	struct.set_positions(struct.get_positions(wrap=True))
	view(struct);
	write_vasp(filename+"tr",struct,direct=True,sort="zsort",vasp5=True)