#!/usr/bin/python2
from ase.io.vasp import read_vasp,write_vasp
from sys import argv,stdout

struct=read_vasp(argv[1])
#mul=20/0.53
mul=15/0.53
ngx=struct.cell[0,0]*mul;
ngy=struct.cell[1,1]*mul;
ngz=struct.cell[2,2]*mul;

stdout.write("NGX=%d\nNGY=%d\nNGZ=%d\n"%(ngx,ngy,ngz));
stdout.write("NGXF=%d\nNGYF=%d\nNGZF=%d\n"%(ngx,ngy,ngz));